"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.app = void 0;
const express_1 = __importDefault(require("express"));
const helmet_1 = __importDefault(require("helmet"));
const error_middleware_1 = require("./middlewares/error.middleware");
const cors_1 = require("./config/cors");
const request_logger_middleware_1 = require("./middlewares/request-logger.middleware");
const rate_limit_middleware_1 = require("./middlewares/rate-limit.middleware");
const auth_route_1 = require("./routes/auth.route");
const admin_route_1 = require("./routes/admin.route");
const auth_middleware_1 = require("./middlewares/auth.middleware");
const event_route_1 = require("./routes/event.route");
const user_route_1 = require("./routes/user.route");
const booking_route_1 = require("./routes/booking.route");
const app = (0, express_1.default)();
exports.app = app;
app.use((0, helmet_1.default)());
app.use(cors_1.corsConfig);
app.use(express_1.default.json());
app.use(request_logger_middleware_1.requestLogger);
app.use(rate_limit_middleware_1.rateLimitMiddleware);
app.use('/api/v1/auth', (0, auth_route_1.authServiceProxy)());
app.use('/api/v1/admins', auth_middleware_1.authMiddleware, (0, admin_route_1.adminServiceProxy)());
app.use('/api/v1/events', auth_middleware_1.authMiddleware, (0, event_route_1.eventServiceProxy)());
app.use('/api/v1/users', auth_middleware_1.authMiddleware, (0, user_route_1.userServiceProxy)());
app.use('/api/v1/bookings', auth_middleware_1.authMiddleware, (0, booking_route_1.bookingServiceProxy)());
app.use(error_middleware_1.errorMiddleware);
